// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8PxRYd84l0SzK6_0nkaKyJ3mccfviHmI',
    appId: '1:830798650861:web:fdd7adafef866b9175dbe4',
    messagingSenderId: '830798650861',
    projectId: 'boviframe-b5c2c',
    authDomain: 'boviframe-b5c2c.firebaseapp.com',
    storageBucket: 'boviframe-b5c2c.firebasestorage.app',
    measurementId: 'G-KVZEV1BWZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzeMkoDFSQIOxZKrCevlyPdSEwoeTrmh0',
    appId: '1:830798650861:android:ab96ba2ae9609a1875dbe4',
    messagingSenderId: '830798650861',
    projectId: 'boviframe-b5c2c',
    storageBucket: 'boviframe-b5c2c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2HHIFYHN3WVLEHdLmjmHkkuieYj4QeY',
    appId: '1:830798650861:ios:5d377020f610896775dbe4',
    messagingSenderId: '830798650861',
    projectId: 'boviframe-b5c2c',
    storageBucket: 'boviframe-b5c2c.firebasestorage.app',
    iosBundleId: 'com.example.boviframe',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG2HHIFYHN3WVLEHdLmjmHkkuieYj4QeY',
    appId: '1:830798650861:ios:5d377020f610896775dbe4',
    messagingSenderId: '830798650861',
    projectId: 'boviframe-b5c2c',
    storageBucket: 'boviframe-b5c2c.firebasestorage.app',
    iosBundleId: 'com.example.boviframe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8PxRYd84l0SzK6_0nkaKyJ3mccfviHmI',
    appId: '1:830798650861:web:69f28e1056c5380775dbe4',
    messagingSenderId: '830798650861',
    projectId: 'boviframe-b5c2c',
    authDomain: 'boviframe-b5c2c.firebaseapp.com',
    storageBucket: 'boviframe-b5c2c.firebasestorage.app',
    measurementId: 'G-TD1VNY4CJ6',
  );
}
